config/routes.rb
Rails.application.routes.draw do

  root 'homepage#home'

  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:show, :create, :new] do 
    resources :dogs, only: [:new, :create, :index, :edit, :show, :update]
    resources :dogs, only: [:show] do
      resources :photos, only: [:new, :create, :show, :index]
    end
  end

  resources :photos, only: [:show] do 
    resources :comments, only: [:new, :create, :edit, :destroy, :update]
  end

  delete '/users/:user_id/dogs/:id', :to => 'dogs#destroy', :as => 'user_dog_delete'
  
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :dog, optional: true 
  belongs_to :photo, optional: true 
  belongs_to :user

  validate :comment_too_long, on: :create
end

def comment_too_long
  if self.content.length > 50
    errors.add(:content, "- too long. Max length is 50.")
  end
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy

  validates :name, :age, :breed, :hobbies, :bio, presence: true 

  scope :sort_name, -> { order(:name) }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :dog
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  
  has_one_attached :image_file

end

app/models/user.rb
class User < ApplicationRecord
    has_many :dogs, dependent: :destroy
    has_many :comments
    has_many :photos, through: :comments
    
    validates :name, presence: true
    
    validates :email, presence: true, 
        uniqueness: { case_sensitive: false }, 
        length: { maximum: 105 }
         
    has_secure_password

    def self.create_by_google_omniauth(auth)
      self.find_or_create_by(name: auth[:info][:email]) do |u|
        u.email = auth[:info][:email]
        u.password = SecureRandom.hex
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
 

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user 
  end


  def record_not_found(err)
    redirect_to :root, notice: err
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :set_comment, only: [:edit, :destroy, :update, :show]
   
    def create
        @photo = Photo.find(params[:photo_id])
        comment = Comment.new(comment_params)
        comment.photo_id = @photo.id 
        comment.dog_id = @photo.dog_id
        comment.user_id = Dog.find(@photo.dog_id).user_id
        comment.save
        redirect_back(fallback_location: root_path)
    end

    def user_create
      comment = Comment.new(comment_params)
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :dog_id)
    end

    def set_comment
        @comment = Comment.find(params[:photo_id])
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

    before_action :set_user
    before_action :set_dog, only: [:show, :edit, :update, :destroy]

    def new
        @dog = Dog.new
    end

    def show
    end

    def create
        @dog = Dog.new(dog_params)
        @dog.user_id = current_user.id 
        if @dog.save
          redirect_to user_dog_url(@user, @dog)       
        else
          render :new
        end
    end

    def edit
    end

    def update
      if @dog.update(dog_params)
        redirect_to user_dog_url(@user, @dog)     
      else
        render :edit
      end
    end 

    def destroy
        @dog.destroy 
        redirect_to user_url(@user)
    end 

    private

    def dog_params
        params.require(:dog).permit(:name, :age, :breed, :hobbies, :bio, :user_id)
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_dog
      @dog = @user.dogs.find(params[:id])
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    def home 
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

    before_action :set_user
    before_action :set_dog

    def index     
      if @dog 
        @photos = @dog.photos  
      end
    end
    
    def new
        @photo = Photo.new
    end

    def create
        @photo = Photo.new(photo_params)
        @photo.dog_id = params[:dog_id]
        if @photo.save!
            redirect_to user_dog_photos_url(@user, @dog)
        else
            render :new
        end
    end 

    def show
        @photo = @dog.photos.find(params[:id])
    end

    private

    def photo_params
        params.require(:photo).permit(:caption, :dog_id, :image_file) 
    end

    def set_dog
        @dog = @user.dogs.find params[:dog_id]
    end

    def set_user
      @user = User.find(params[:user_id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
        session[:user_id] = user.id
        flash[:msg] = "Logged in successfully"
        redirect_to user_path(user)
    else 
      redirect_to login_path 
    end
  end

  def destroy
      session.delete(:user_id)
      flash[:notice] = "You have successfully logged out."
      redirect_to '/'
  end

  def omniauth 
    @user = User.create_by_google_omniauth(auth)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to '/'
    end
    
  end

  private
  def auth
    request.env['omniauth.auth']
  end

  def session_params
    params.require('session').permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
        @dog = Dog.new
    end

    def show
        @photos = current_user.photos.uniq
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:msg] = "Logged in successfully"
            redirect_to user_url(@user)
        else
            flash[:errors] = @user.errors.full_messages
            render :new 
        end
    end
   

    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dogs/edit.html.erb
<h1>Dog's edit page </h1>

 <%= render partial: 'layouts/errors', locals: {object: @dog} %>

<%= form_for @dog, url: { action: "update"} do |f| %>
    <%= f.label :Name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :Age %>
    <%= f.text_field :age %>
    <br>
    <%= f.label :Breed %>
    <%= f.text_field :breed %>
    <br>
    <%= f.label :Hobbies %>
    <%= f.text_field :hobbies %>
    <br>
    <%= f.label :Bio %>
    <%= f.text_field :bio %>
    <br>
    <br>
    <%= f.submit "Update" %>
    <br>
    <br>
    <%= link_to "Cancel", user_dog_path(@user, @dog) %>
<br>
<% end %>

app/views/dogs/new.html.erb
<h1> Create Dog Profile </h1>

<%= form_for @dog, url: { action: "create" } do |f| %>

  <%= render partial: 'layouts/errors', locals: {object: @dog} %>

  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :age %>
  <%= f.number_field :age %><br>
  <%= f.label :breed %>
  <%= f.text_field :breed %><br> 
  <%= f.label :hobbies %>
  <%= f.text_field :hobbies %><br> 
  <%= f.label :bio %>
  <%= f.text_field :bio %><br> 
  <br>
  <br>
  <%= f.submit "Submit"%>
  <br>
  <br>
  <%= link_to "Cancel", user_path(@user) %>  
<% end %>

app/views/dogs/show.html.erb
Name: <%= @dog.name %>
<br>
Age: <%= @dog.age %>
<br>
Breed: <%= @dog.breed %>
<br>
Hobbies: <%= @dog.hobbies %>
<br>
Bio: <%= @dog.bio %>
<br> 
<br>
<br>
<%= link_to "See Photo", user_dog_photos_path(@user, @dog) %>
<br>
<%= link_to 'Edit', edit_user_dog_path(@user, @dog) %>
<br>
<%= link_to 'Delete', user_dog_delete_path(@user, @dog), method: :delete %>
<br>
<br>
<%= link_to 'Done', user_path(@user) %>

app/views/homepage/home.html.erb
<h1>Welcome to Sniff n Play</h1>
<%# <% if current_user %>
  <%# <%= link_to "Logout", destroy_user_path, method: :delete %> 
<%# <% else %> 
  <%= link_to "Sign up", signup_path %><br> 
  <%= link_to "Login", login_path %>
  <br>
  <br>
  <%= link_to "Sign in with Google", "/auth/google_oauth2" %>
<%# <% end %> 

app/views/layouts/_all_photos.html.erb
<ul>
  <% photos.each do |photo| %>
    <% comments = photo.comments %>
    <% comment_text = '' %>
    <% if comments.count > 0 %>
      <% comments.each.with_index(1) do |cmt, idx| %>
        <% if cmt.content.length > 0 %>
          <% if idx == 1 %>
            <% comment_text = "#{idx}. " + cmt.content %> 
          <% else %>
          <% comment_text = comment_text + "&#13;&#10;#{idx}. "+ cmt.content %> 
          <% end %>   
        <% end %>
      <% end %>
      <% else %>
        <% comment_text ="No Comment Yet!" %>
      <% end %> 
    <li>
      <div>
        <% if photo.image_file.attached? %>
          <span style="color:#1c87c9"><%= photo.caption %></span> </p>
          <div style="height: 165px;width: 360px;">
            <span style="display: inline-block"><%= image_tag(photo.image_file, width: 128) %></span>
            <div style="display: inline-block;height: 100%;width: 62%;" ><textarea style="display: inline-block;height: 75%;width: 75%;"><%= comment_text.html_safe() %></textarea></div>
          </div>
          <% if allow_add_comment %>
            <% new_comment = Comment.new %>
            <%=form_with model: new_comment, url: photo_comments_path(photo) do |f|%>

            <%= render partial: 'layouts/errors', locals: {object: new_comment} %>

              <h5>Enter your comment below ↓</h5>
              <strong><%=f.text_field :content,size: 50, placeholder: "type your comment on this line"%> </strong>
              <%= f.submit "comment" %>
            <% end %>
          <% end %>  
        <% else %>
            "No Photo"
        <% end %>
      </div>
    </li>
    <br>
  <% end %>
</ul>
<br>

app/views/layouts/_commented_photos.html.erb
<ul>
  <% photos.each do |photo| %>
    <% comments = photo.comments %>
    <% comment_text = '' %>
    <% if comments.count > 0 %>
      <% comments.each.with_index(1) do |cmt, idx| %>
        <% if cmt.content.length > 0 %>
          <% if idx == 1 %>
            <% comment_text = "#{idx}. " + cmt.content %> 
          <% else %>
          <% comment_text = comment_text + "&#13;&#10;#{idx}. "+ cmt.content %> 
          <% end %>   
        <% end %>
      <% end %>
      <% else %>
        <% comment_text ="No Comment Yet!" %>
      <% end %> 
    <li>
      <div>
        <% if photo.image_file.attached? %>
          <span style="color:#1c87c9"><%= photo.caption %></span> </p>
          <div style="height: 165px;width: 360px;">
            <span style="display: inline-block"><%= image_tag(photo.image_file, width: 128) %></span>
            <div style="display: inline-block;height: 100%;width: 62%;" ><textarea style="display: inline-block;height: 100%;width: 100%;"><%= comment_text.html_safe() %></textarea></div>
          </div>
          <% if allow_add_comment %>
            <% new_comment = Comment.new %>
            <%=form_with model: new_comment, url: photo_comments_path(photo) do |f|%>

            <%= render partial: 'layouts/errors', locals: {object: new_comment} %>

              <h5>Enter your comment below ↓</h5>
              <strong><%=f.text_field :content,size: 50, placeholder: "type your comment on this line"%> </strong>
              <%= f.submit "comment" %>
            <% end %>
          <% end %>  
        <% else %>
            "No Photo"
        <% end %>
      </div>
    </li>
    <br>
  <% end %>
</ul>
<br>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sniff n Play</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
    <%= link_to 'Log Out', logout_path, method: :delete %>
  </div>
  <body>
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end -%>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<% if logged_in? && (@dog.user == current_user) %> 

<h1> List of photos of <%= @dog.name %> </h1>
<%= render partial: 'layouts/commented_photos', locals: {photos: @photos, allow_add_comment: true} %>

<% if @dog.photos.count < 5 %>
  <%= link_to "Add More Photo", new_user_dog_photo_path(@user, @dog) %> 
<% end %>  
<br>
<br>  
<%= link_to "Done", user_dog_path(@user, @dog) %> 
<br>
<br>
<br>
<% else %> 
    <h1>not your page</h1>
<%end %>

app/views/photos/new.html.erb
<h1> Upload photo here </h1>

<%= form_for @photo, url: { action: "create" } do |f| %>

  <%= f.label :image_file %>
  <%= f.file_field :image_file %>

  <p>
  <%= f.label :caption %>
  <%= f.text_field :caption %>
  </P>
  <%= f.submit "Upload" %>
  <br>
  <br>
  <%= link_to "Cancel", :back %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1> 

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :email %>
  <%= f.email_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br> 
  <%= f.submit "SignUp"%>
  <br>
  <br>  
  <%= link_to "Back", :back %>
<% end %>

app/views/users/show.html.erb
<% if logged_in? && (current_user == @user) %>

<h1> Welcome <%=@user.name %></h1>
<h2> Your Dogs: </h2>
  <% @user.dogs.sort_name.each do |dog| %>
    <%= link_to dog.name, user_dog_path(@user, dog) %>
    <br>
  <% end %>

<br>
<br>
<br>

<h4> Your Commented Photos: </h4>

<%= render partial: 'layouts/commented_photos', locals: {photos: @photos, allow_add_comment: false} %>


<%= link_to 'Create Your Dog Profile', new_user_dog_path(@user) %>
  
<%end%>


    